// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRunningTask() {
  return window['go']['app']['App']['CancelRunningTask']();
}

export function CheckMicrophoneAccess() {
  return window['go']['app']['App']['CheckMicrophoneAccess']();
}

export function CheckScreenCapturePermission() {
  return window['go']['app']['App']['CheckScreenCapturePermission']();
}

export function ClearResume() {
  return window['go']['app']['App']['ClearResume']();
}

export function ClearScreenshots() {
  return window['go']['app']['App']['ClearScreenshots']();
}

export function CopyCode() {
  return window['go']['app']['App']['CopyCode']();
}

export function EmitEvent(arg1, arg2) {
  return window['go']['app']['App']['EmitEvent'](arg1, arg2);
}

export function GetDomainCategories() {
  return window['go']['app']['App']['GetDomainCategories']();
}

export function GetInitStatus() {
  return window['go']['app']['App']['GetInitStatus']();
}

export function GetModels(arg1) {
  return window['go']['app']['App']['GetModels'](arg1);
}

export function GetResumePDF() {
  return window['go']['app']['App']['GetResumePDF']();
}

export function GetScreenshotPreview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetScreenshotPreview'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function IsInterruptThinkingEnabled() {
  return window['go']['app']['App']['IsInterruptThinkingEnabled']();
}

export function MoveWindow(arg1, arg2) {
  return window['go']['app']['App']['MoveWindow'](arg1, arg2);
}

export function OpenMicrophoneSettings() {
  return window['go']['app']['App']['OpenMicrophoneSettings']();
}

export function OpenScreenCaptureSettings() {
  return window['go']['app']['App']['OpenScreenCaptureSettings']();
}

export function ParseResume() {
  return window['go']['app']['App']['ParseResume']();
}

export function RemoveFocus() {
  return window['go']['app']['App']['RemoveFocus']();
}

export function RemoveLastScreenshot() {
  return window['go']['app']['App']['RemoveLastScreenshot']();
}

export function RemoveScreenshot(arg1) {
  return window['go']['app']['App']['RemoveScreenshot'](arg1);
}

export function RequestMicrophoneAccess() {
  return window['go']['app']['App']['RequestMicrophoneAccess']();
}

export function RequestScreenCapturePermission() {
  return window['go']['app']['App']['RequestScreenCapturePermission']();
}

export function RestoreFocus() {
  return window['go']['app']['App']['RestoreFocus']();
}

export function SaveImageToFile(arg1) {
  return window['go']['app']['App']['SaveImageToFile'](arg1);
}

export function ScrollContent(arg1) {
  return window['go']['app']['App']['ScrollContent'](arg1);
}

export function SelectResume() {
  return window['go']['app']['App']['SelectResume']();
}

export function SetWindowAlwaysOnTop(arg1) {
  return window['go']['app']['App']['SetWindowAlwaysOnTop'](arg1);
}

export function Show() {
  return window['go']['app']['App']['Show']();
}

export function StartRecordingKey(arg1) {
  return window['go']['app']['App']['StartRecordingKey'](arg1);
}

export function StopRecordingKey() {
  return window['go']['app']['App']['StopRecordingKey']();
}

export function TestConnection(arg1, arg2) {
  return window['go']['app']['App']['TestConnection'](arg1, arg2);
}

export function ToggleClickThrough() {
  return window['go']['app']['App']['ToggleClickThrough']();
}

export function ToggleVisibility() {
  return window['go']['app']['App']['ToggleVisibility']();
}

export function TriggerDeleteScreenshot() {
  return window['go']['app']['App']['TriggerDeleteScreenshot']();
}

export function TriggerScreenshot() {
  return window['go']['app']['App']['TriggerScreenshot']();
}

export function TriggerSend() {
  return window['go']['app']['App']['TriggerSend']();
}

export function TriggerSolve() {
  return window['go']['app']['App']['TriggerSolve']();
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}
